create table bookings
(
    id                      bigint generated by default as identity,
    expected_return_date    date not null,
    rental_date             date not null,
    user_id                 bigint not null,
    primary key (id)
);
alter table bookings add constraint FKeyog2oic85xg7hsu2je2lx3s6 foreign key (user_id) references users;
